image: docker:stable

options:
  docker: true

pipelines:
  default:
    - step:
        script:
          - chmod +x .bitbucket/dependencies.sh
          - .bitbucket/dependencies.sh
          - chmod 777 var/elasticsearch-data
          - make build-test
          - make start-test
          - docker ps -a
          - make wait-for-db
          - make drop-migrate
          - make generate-jwt-keys
          - make create-roles-groups
          - make migrate-cron-jobs
          - make messenger-setup-transports
          - make wait-for-elastic
          - make elastic-create-or-update-template
          - make info
          - make phpunit
          - make composer-audit
          - make ecs
          - make phpcs
          - make phpstan
          - make phpinsights
          - make phpmd
          - make phpcpd
          - make stop-test
